MODEL:
  META_ARCHITECTURE: "QueryDet"
  WEIGHTS: "/home/akhil135/PhD/DroneDetectron2/pretrained_models/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]      
  ANCHOR_GENERATOR:
    NAME: "AnchorGeneratorWithCenter"
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3)] for x in [16, 32, 64, 128, 256, 512]]"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    NUM_CLASSES: 10
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6", "p7"]  
  QUERY:
    Q_FEATURE_TRAIN: [1, 2]
    FEATURES_WHOLE_TEST: [2, 3, 4, 5]
    FEATURES_VALUE_TEST: [0, 1]
    Q_FEATURE_TEST: [1, 2]
    QUERY_LOSS_WEIGHT: [10., 10.]
    QUERY_LOSS_GAMMA: [1.3, 1.3]
    ENCODE_CENTER_DIS_COEFF: [1., 1.]
    ENCODE_SMALL_OBJ_SCALE: [[0, 32], [0, 64]]    
    QUERY_INFER: False
  CUSTOM:
    GRADIENT_CHECKPOINT: False
    USE_LOOP_MATCHER: True
    FOCAL_LOSS_ALPHAS: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    FOCAL_LOSS_GAMMAS: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
    CLS_WEIGHTS: [1.0, 1.4, 1.8, 2.2, 2.6, 2.6]
    REG_WEIGHTS: [1.0, 1.4, 1.8, 2.2, 2.6, 2.6]

DATASETS:
  TRAIN: ("visdrone_2019_train",)
  TEST: ("visdrone_2019_val",)
DATALOADER:
  NUM_WORKERS: 4
  SUP_PERCENT: 10.0
  USE_RANDOM_SPLIT: True
  RANDOM_DATA_SEED: 42
  SEED_PATH: "dataseed/visdrone_sup_5.0.txt"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (12000, 18000)
  MAX_ITER: 25000
  CHECKPOINT_PERIOD: 2000
  AMP:
    ENABLED: True
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: value
    CLIP_VALUE: 30.0
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (1000, 1100, 1200) #(800, 900, 1000, 1100, 1200)
  MAX_SIZE_TRAIN: 1999
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1999
VERSION: 2
TEST:
  EVAL_PERIOD: 2000
  DETECTIONS_PER_IMAGE: 800